### ISSUE TITLE
When build, the visualization stops working

### ISSUE THREAD

**Issue by Netterric** [hallidev/UnityWASAPILoopbackAudio#1]
Using Unity 2019.2.3f1
On "Play" work

**Comment by hallidev** [comment]
Need to make sure to change API Compatibility Level to .NET 4.X

From readme:
3: IMPORTANT! If you are going to be making a build using this, you need to go to Edit -> Project Settings -> Player -> Api Compatibility Level and set it to ".NET 2.0". Otherwise you will get a kernel exception upon trying to run Unity Player.

**Comment by Netterric** [comment]
But readme said set Api Compatibility Level to ".NET 2.0"
Ah, you already fixed

**Comment by Netterric** [comment]
Thanks
